#!/bin/bash

if [ "$#" -eq 0 ] 
then
    echo "Nothing to clone"
else 
    if [ "$#" -gt 0 ]
    then
        name=''
        if [ "$#" -eq 1 ] 
        then
            fname="$(basename $1)"
            name="${fname/.*/}"
        else
            name="$2"
        fi
        git clone $1 $name
        cd $name
        echo -en "\033]0;${name}\a"
        /home/l.hoflay/dev/tabs/tabs write -n $name -p $PWD
    fi
fi
